# -*- coding: utf-8 -*-
"""example_04_Comparison_Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nM4l_k-tRLd-DwyG-EK4cWAsq6h2eNNw
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Comparison Operators

a = 3
b = 4

print(a == b)  # is false - If the values of two operands are equal, then the condition becomes true.
print(a != b)  # is true  - If values of two operands are not equal, then condition becomes true.
print(a > b)   # is false - If the value of left operand is greater than the value of right operand, then condition becomes true.
print(a < b)   # is true  - If the value of left operand is less than the value of right operand, then condition becomes true.
print(a >= b)  # is false - If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.
print(a <= b)  # is true  - If the value of left operand is less than or equal to the value of right operand, then condition becomes true.
