# -*- coding: utf-8 -*-
"""Exercise_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6d0tpkHVm8VriBWWaHt5Zqx3e4MYSYO
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Resolution of Exercise 01

age = int(input("Enter your age: "))
 
if age >= 18:
     print("Of legal age")
elif age < 18:
     print("Underage")