# -*- coding: utf-8 -*-
"""example_06_Conditional_Statements_IF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TicuhnRtO_HkyjGMUt7F3ktVNRMqSNaM
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Conditional Statements 

a = 1
b = 1000000
if a > b:
  print("a is greater than b.")
if b > a:
  print("b is greater than a.")
