# -*- coding: utf-8 -*-
"""example_07_Conditional_Statements_ELSE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5bKC_VYoHNzAjrTeXqVxGgwTwtepZN7
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Conditional Statements 

a = 1
b = 2
if a > b:
  print("a is greater than b.")
else:
  print("a is not greater than b.")