# -*- coding: utf-8 -*-
"""example_12_String_Part_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpkP94fanjaa0FWAXtaM21RGwa06Bx2Y
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 14, 2021

# String Methods: Part 1

# String concatenation means add strings together. Use the + character to add a variable to another variable:

a = "Concatenating"
b = "words"
c = a + " " + b  # To add a space between them, add a " ".
print(c)

# To get the length of a string, use the len() function. The len() function returns the length of a string:

text = "Charles Fernandes de Souza"
print(len(text))

# Indexing allows you to access individual characters in a string directly by using a numeric value. 
# String indexing is zero-based: the first character in the string has index 0, the next is 1, and so. 

sequence = "Charles Fernandes de Souza"

letter = sequence[0]
print (letter)
letter = sequence[8]
print (letter)
letter = sequence[21]
print (letter)
letter = sequence[8:17]
print (letter)