# -*- coding: utf-8 -*-
"""example_13_String_Part_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzwSQ7CXNm30gzYp0yGAQ0JyDHUDyVFg
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 14, 2021

# String Methods Part 2

a = "Concatenating"
b = "words"
c = a + " " + b  # To add a space between them, add a " ".
print(c)

# The .upper() and .lower() string methods are self-explanatory. 
print(c.upper()) # Performing the .upper() method on a string converts all of the characters to uppercase, 
print(c.lower()) # whereas the lower() method converts all of the characters to lowercase.

# The .strip() string methods
d = "             strip example         "
print(d)
print(d.strip()) #Remove spaces at the beginning and at the end of the string

# The .split() string methods
e = "The split() method splits a string into a list."
f = e.split()
print(f)

# The .find() string methods
txt = "The way to get started is to quit talking and begin doing. - Walt Disney"
search = txt.find("started") # We search for a specific character or characters in a string with the .find() method.
print(search)

# The .find() string methods
txt = "The way to get started is to quit talking and begin doing. - Walt Disney"
print(txt)
txt = txt.replace("talking", "silent") # The .replace() method replaces a specified phrase with another specified phrase.
print(txt)

