# -*- coding: utf-8 -*-
"""Exercise_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNwWnwkpmDdHbSfwApwTXeyV8eKIJSlf
"""

# Course title: Udemy Course - Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Resolution of Exercise 04

list_Exercise_04 = [999, 99, 9]
print(list_Exercise_04)
list_Exercise_04.sort()
print(list_Exercise_04)