# -*- coding: utf-8 -*-
"""Exercise_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ng3JLptC1Nw-H8Our6VGEznDKMrVbv5j
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Resolution of Exercise 02

grade_01 = float(input("Enter the first grade: "))
grade_02 = float(input("Enter the second grade: "))
 
average = (grade_01 + grade_02)/2
print("Your average is", average) 
if average >= 6:
     print("Status: Approved")
else:
     print("Status: Failed")