# -*- coding: utf-8 -*-
"""example_02_Arithmetic_Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oUAV73jB3Aa9qTsxhV3khPGEUAH-Yfn6
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 10, 2021

# Arithmetic Operations

print(2+2)  #  +  Addition
print(2-2)  #  -  Subtraction
print(2*2)  #  *  Multiplication
print(2/2)  #  /  Division
print(2%2)  #  %  Modulus
print(2**2) #  ** Exponent
print(2//2) #  // Floor Division
