# -*- coding: utf-8 -*-
"""example_03_Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbXUEUlml7rDXmdLx1O1XRyabt5N6eIA
"""
# Course title: Udemy - Introducao a linguagem Python
# Instructor: Prof. Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 10, 2021

# Variables

variable_01 =  100        # An integer assignment
variable_02 =  10.10      # A floating point
variable_03 =  "Writing"  # A string content
variable_04 =  True       # A boolean type 
variable_05 =  False      # A boolean type 

print(variable_01)
print(variable_02)
print(variable_03)
print(variable_04)
print(variable_05)
