# -*- coding: utf-8 -*-
"""example_18_List_Part_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ArfUfA8OX46XU6ku5dcIOh1p9gS7f4Y
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# List Part 02

# List Methods in Python

# sort() :- This function sorts the list in increasing order:
list_example = [5, 8, 3, 6, 1, 4, 9, 2, 7]
print(list_example)
list_example.sort()
print(list_example)

# reverse() :- This function reverses the elements of list:
list_example.reverse()
print(list_example)

# Example with string:
string_list = ["Kangaroo", "Rabbit", "Hippopotamus ", "Dolphin", "Alligator", "Turtle", "Chameleon"]
print(string_list)
string_list.sort()
print(string_list)
string_list.reverse()
print(string_list)
