# -*- coding: utf-8 -*-
"""example_17_List_Part_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KHI6mH_3LlSBR-_RZwn7sJuGeTu1_FZc
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# List Part 01

# Lists are used to store multiple items in a single variable:
mylist = ["apple", "banana", "cherry"]
print(mylist)

# List items can be of any data type:
list_01 = ["apple", "banana", "cherry"]
print(list_01)
list_02 = [10, 20, 30]
print(list_02)
list_03 = [10, "apple", 20, "banana", 30, "cherry"]
print(list_03)

# Printing value by index:
print(list_03[3])

# Inside the for loop, on every iteration, you print out the list value:
for index in list_03:
  print(index)

#To determine how many items a list has, use the len() function:
thislist = [10, "apple", 20, "banana", 30, "cherry", 40, "avocado", 50] 
print(len(thislist))

# Add a new item to the list , use the append() function:
thislist.append("Watermelon")
print(thislist)

# Check if Item Exists - To determine if a specified item is present in a list use the in keyword:
thislist = [10, "apple", 20, "banana", 30, "cherry", 40, "avocado", 50] 
if "cherry" in thislist:
  print("Yes, 'apple' is in the fruits list")

# This method deletes all the elements in range starting from index ‘a’ till ‘b’ mentioned in arguments:

del thislist[3 : 7]
print(thislist)
