# -*- coding: utf-8 -*-
"""example_20_Random_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QX1QSIHAZXKRQuAVBVt71HPVGQ_oPjam
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Random Numbers

# The random() method in random module generates a number between 0 and ...

import random

# The randint() method generates a integer between a given range of numbers:
number = random.randint(0,10)
print(number)

# We can use the above randint() method along with a for loop to generate a list of numbers:
listRandom = []
for i in range(0,10):
  number = random.randint(1,30)
listRandom.append(number)
print(listRandom)

# The random choice() function to select a random item from a List and Set. 
# Choose a random item from a sequence. Here seq can be a list, tuple, string, or any iterable like range:

listRandom  = [100, 200, 300, 400, 500]
print(random.choice(listRandom ))
