# -*- coding: utf-8 -*-
"""example_08_Conditional_Statements_ELIF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpALgAiJWgeGbdQ2Bpx3a3cZ-Ju3r3to
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Conditional Statements

a = 2
b = 2

if b > a:
  print("b is greater than a.")
elif a == b:
  print("a and b are equal.")
else:
  print("a is greater than b.")