# -*- coding: utf-8 -*-
"""example_15_manipulate_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZNIPzeR9IDIm7QhOqMAacicEdKTgW-_w
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 14, 2021

# Manipulate Files

# In Python, a file operation takes place in the following order:
# 1. Open a file
# 2. Read or write (perform operation)
# 3. Close the file

# Python File Open

f = open("poem.txt", "r") # The open() function returns a file object, 
print(f.read()) # which has a read() method for reading the content of the file:

f = open("poem.txt", "r") # The open() function returns a file object, 
print(f.readlines()) #  return one line by using the readline() method:

print("\n")

f = open("poem.txt", "r") # By looping through the lines of the file, you can read the whole file, line by line:
for x in f:
  print(x)

f.close() # Close the file when you are finish
