# -*- coding: utf-8 -*-
"""example_09_Iteration_Statements_WHILE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulG921KmJdDLgNwxOvlHPcffEag4P8e9
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Iteration Statements

# While Loop In Python is used to execute a block of statement as long as a given condition is true. 
# And when the condition is false, the control will come out of the loop.
# The condition is checked every time at the beginning of the loop.

x = 0
while (x < 10):
   print(x)
   x += 1   # It adds right operand to the left operand and assign the result to left operand:	x += 1 is equivalent to  x = x + 1
