# -*- coding: utf-8 -*-
"""example_10_Iteration_Statements_FOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MmI-sUuCr-vDMlyvlAZyfBX1VucIRv2
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Iteration Statements

# For loop in Python is used to iterate over items of any sequence, such as a list or a string.

list_01 = [1, 2, 3, 4, 5] # The list is the most versatile datatype available in Python, which can be written as a list of comma-separated values (items) between square brackets. 
list_02 = ["Content", "written in", "a list"] 
list_03 = [0, "string", "word", "term", 9.99, True] # Important thing about a list is that the items in a list need not be of the same type.

for i in list_01:
	print(i)

for i in list_02:
	print(i)

for i in list_03:
	print(i)
