# -*- coding: utf-8 -*-
"""example_11_Iteration_Statements_FOR_RANGE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gnPsc5QgVuOuRJUubaJCOMXZ-6JX9IsG
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Iteration Statements

# The range() function is a built-in that is used to iterate over a sequence of numbers.

for i in range(5):
   print(i)

for i in range(11,19):
   print(i)   

for i in range(11,19,2): # using step parameter
   print(i)