# -*- coding: utf-8 -*-
"""example_05_Logical_Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkCY2sUmUxqdCC0U-08Tqhpu85USNbCf
"""

# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 13, 2021

# Logical Operators

a = True
b = False
print(a and b)          #is False - If both the operands are true then condition becomes true.
print(a or b)           #is True  - If any of the two operands are non-zero then condition becomes true.
negation = not(a and b) #is True  - Used to reverse the logical state of its operand.
print(negation)