# -*- coding: utf-8 -*-
"""example_24_Map_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpMlo7fxwXNU1zi2X9JoEpN1mvORM_c8
"""

# Course title: Udemy Course - Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Map Function

# The map() function executes a specified function for each item in an iterable. The item is sent to the function as a parameter:
def double(x):
  return x*2

value = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

double_value = map(double, value)

for v in double_value:
  print(v)

# Calculate the length of each word in the tuple:
def animals(a):
  return len(a)

list_animals = map(animals, ("elephant", "giraffe", "moose", "penguin", "squirrel"))

#convert the map into a list, for readability:
print(list(list_animals))