# -*- coding: utf-8 -*-
"""example_25_Reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahHgbkOfyK82e23Zjyeryq_XUSPMMnv3
"""
# Course title: Udemy Course - Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Reduce

# Reduce() is a function that implements a mathematical technique called folding or reduction. 
# It is useful when you need to apply a function to an iterable and reduce it to a single cumulative value.

from functools import reduce

def soma(x, y):
	return x+y

lista = [1, 3, 5, 10, 20]

soma = reduce(soma, lista)
print(soma)
