# -*- coding: utf-8 -*-
"""example_26_Filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u7EsNC6CWTwkjnkKKMYK8k0tiS-xtZCI
"""
# Course title: Udemy Course - Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Filter Function

# The filter() function returns an iterator were the items are filtered through a function to test if the item is accepted or not:

ages = [5, 4, 9, 12, 15, 18, 27, 36, 45, 54]

def isAdult(age): 
  if age < 18:
    return False
  else:
    return True

adults = filter(isAdult, ages) # Filter the array, and return a new array with only the values equal to or above 18. 

for i in adults:
  print(i)
