# -*- coding: utf-8 -*-
"""example_22_List_Comprehensions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPg-sIuNsxvrv--CDaBQyymalHfGO3Bn
"""
# Course title: Udemy Course - Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# List Comprehension

# List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list:
x = [0, 1, 2, 3, 4, 5 , 6, 7, 8, 9]
y = [i**2 for i in x]
print(x)
print(y)
# The condition is like a filter that only accepts the items that valuate to True:
z = [i for i in x if i % 2 == 1]
print(z)
# The iterable can be any iterable object, use the range() function to create an iterable:
k = [i for i in range(10) if i < 10]
print(k)
